### ISSUE TITLE
Bundler::GemRequireError: There was an error while trying to load the gem 'vigia'

### ISSUE THREAD

**Issue by romaintb** [nogates/vigia#18] opened 2016-01-07 14:47 UTC
Hi,

I get the following error : 
```
▶ bundle exec rake
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'vigia'.
/home/romain/work/xxx/config/application.rb:16:in `<top (required)>'
/home/romain/work/xxx/Rakefile:5:in `require'
/home/romain/work/xxx/Rakefile:5:in `<top (required)>'
NameError: method `describe' not defined in #<Class:0x005626ca53dc60>
/home/romain/work/xxx/config/application.rb:16:in `<top (required)>'
/home/romain/work/xxx/Rakefile:5:in `require'
/home/romain/work/xxx/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```
Here is my Gemfile :
```
source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'rails-api'
gem 'pg', '~> 0.18.3'
gem 'fog', '~> 1.36.0'
gem 'clockwork', '~> 1.2.0'

group :staging do
  gem 'unicorn', '4.9.0'
end

group :development, :test do
  gem 'minitest-vcr', '~> 1.3.0'
  gem 'rubocop', require: false
  gem 'inch', require: false
end

group :test do
  gem 'codeclimate-test-reporter', require: nil
  gem 'vigia'
end

group :development do
  gem 'spring'
  gem 'pry-rails'
end

gem 'active_model_serializers', '~> 0.9.3'
gem 'devise_token_auth', '~> 0.1.36'
gem 'rack-cors', require: 'rack/cors'
```

I can't find a way to debug this properly, can you help me on that one ?

Thanks !

**Comment by romaintb** [comment] 2016-01-07 15:35
fix it by adding `require: false`, maybe this can go in a doc somewhere ?

**Comment by romaintb** [comment] 2016-01-07 15:39
I managed to get an other error : 
```
NameError: method `describe' not defined in #<Class:0x005651ecc3dc48>
/home/romain/work/xxx/lib/tasks/vigia.rake:4:in `block in <top (required)>'
Tasks: TOP => default => vigia
(See full trace by running task with --trace)
```

**Comment by nogates** [comment] 2016-01-08 05:35
Hello @romaintb.

I managed to reproduce the error. Thanks for providing the Gemfile.

Seems that rails has changed its default `rails_helper` and now comes with `config.expose_dsl_globally` set as fall. Which, to be honest, is the right thing to do.

Unfortunately, Vigia expects that RSpec DSL is available globally, and it shouldn't. I'll fix this soon.

In the meantime, if you don't want to wait, you can always configure RSpec, inside Vigia config, and set this option to `true`

```ruby
Vigia.configure do |config|
  config.rspec_config do |rspec_config|
    rspec_config.expose_dsl_globally = true
  end
end
```

But as I said, this is just a patch and Vigia shouldn't rely on it anyway.

**Comment by nogates** [comment] 2016-01-08 07:35
Hello again @romaintb 

I've released a new version of vigia `0.2.1`. Can you please change your Gemfile to use this version and let me know if it fixes the issue for you?

**Comment by romaintb** [comment] 2016-01-08 11:08
Hi @nogates, that was a quick answer :) Thanks for that.
Unfortunately, it seems I have the same error than previously, even with : 
```
▶ gem list vigia

*** LOCAL GEMS ***

vigia (0.2.1)
```

Let me know if I can help further.

**Comment by romaintb** [comment] 2016-01-08 11:10
Maybe a little more infos can help : 
```
▶ bundle exec rake   
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'vigia'.
/home/romain/work/selfdeploy2/config/application.rb:16:in `<top (required)>'
/home/romain/work/selfdeploy2/Rakefile:5:in `require'
/home/romain/work/selfdeploy2/Rakefile:5:in `<top (required)>'
NameError: method `describe' not defined in #<Class:0x005650801adc50>
/home/romain/work/selfdeploy2/config/application.rb:16:in `<top (required)>'
/home/romain/work/selfdeploy2/Rakefile:5:in `require'
/home/romain/work/selfdeploy2/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

Full trace here : http://pastebin.com/EEYUJDcy

**Comment by nogates** [comment] 2016-01-08 14:05
Oh! Double error! Fun! :)

Could you please paste how are you configuring vigia inside the rake task? 

Also, have you modified anyway the default `spec_helper.rb` or do you have a `.rspec` file in your folder?

**Comment by romaintb** [comment] 2016-01-08 17:25
Sure, here we go : 

``` ruby
▶ cat lib/tasks/vigia.rake 
desc 'Run Vigia tests'
task vigia: :environment do
  # start rails server by the easiest way
  system("bundle exec rails s -e #{Rails.env} -d")

  # give some time to the server
  sleep 10

  Vigia.configure do |config|
    config.adapter     = Vigia::Adapters::Raml
    config.source_file = "#{Rails.root}/api.raml"
    config.host        = 'http://localhost:3000'
  end

  Vigia.rspec!
end
```
``` ruby
▶ cat test/test_helper.rb 
ENV['RAILS_ENV'] ||= 'test'

if ENV['TRAVIS']
  require 'codeclimate-test-reporter'
  CodeClimate::TestReporter.start
end

require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

VCR.configure do |c|
  c.cassette_library_dir = 'test/vcr'
  c.hook_into :typhoeus
end

module ActiveSupport
  #
  class TestCase
    MinitestVcr::Spec.configure!

    # Setup all fixtures in test/fixtures/*.yml for all tests
    # in alphabetical order.
    fixtures :all

    # Add more helper methods to be used by all tests here...
  end
end
```
And no rspec files in folder.

If I set `require false` in the gem file and tries in rails console :
```
▶ bundle exec rails c
Loading development environment (Rails 4.2.4)
[1] pry(main)> require 'vigia'
NameError: method `describe' not defined in #<Class:0x0055e365061c58>
from /home/romain/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/dsl.rb:81:in `remove_method'
[2] pry(main)>
```

Hope this helps :)

**Comment by nogates** [comment] 2016-01-09 09:39
Got it! That was a tricky one.

You are including `minitest-vcr` in your Gemfile, which uses `minitest`, which seems to be declaring the `describe` method inside the main object namespace. Then, when Vigia tries to require `rspec`, it fails internally, because it tries to remove the method from its class but it doesn't exist (https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/dsl.rb#L81)

So, alternatives:

 - if you require vigia before `minitest-vcr`, rake does correctly list the available tasks, but I am not sure if this will break the `minitest` functionality. You should be able to configure `RSpec` to not monkey patch the main object space by using: `config.expose_dsl_globally = false.`, so it shouldn't affect the `minitest` dsl methods (hopefully).

- You can also just load `rspec` before `minitest-vcr`. Given that `RSpec` will already be loaded when vigia requires it, this won't fail. But this solution has the same cons that the previous one.

- Last but not least, you can always run vigia with a different environment, and have different gem groups for vigia and minitest.

I hope this helps. Let me know how it goes!

**Comment by romaintb** [comment] 2016-01-11 13:24
Thanks a lot for debugging this :) Putting vigia before minitest-vcr did the trick.
Now I have an other problem it the raml gem, about some json validation, but I think vigia is now working correctly.

Thanks a lot for your time, I would have been absolutely stuck without your help !
Cheers

**Comment by nogates** [comment] 2016-01-11 22:53
No worries, happy to help! And also, this helped me to fix another bug, so thanks! :)

Closing this, since the problem is not in Vigia anymore.

**Closed by nogates** 2016-01-11 22:53 UTC

**Comment by nsacent** [comment] 2016-09-11 19:47
You should run

`sudo apt-get install nodejs`

to install NodeJS in Ubuntu or

`brew install nodejs`
